#!/bin/sh

total="$(scc --no-cocomo $1 | awk '/^Total/ { printf("%d"), $6 }')"
# -M '.*\.md$|LICENSE$|.*\.txt$'
scc --no-cocomo $1 |
  awk "/^\w/ && !/Processed|Total/ && NR > 2 { printf(\"%f %s\n\", (\$6 / $total), \$1) }" |
  sort -r |
  awk "BEGIN {print \"Usage\tLanguage\" } { printf(\"%.1f%%\t%s\n\", \$1*100, \$2) }"
