#!/usr/bin/env python

from os import listdir, getenv

paths = str(getenv('PATH')).split(':')
execs = []

for dir in paths:
  try:
    execs.extend(listdir(dir))
  except FileNotFoundError:
    pass

execs.sort()
for ex in execs:
  print(ex)
