#!/bin/sh

user=$USER
device=$1
mountName=$2

[ -z "$device" ] \
	&& echo "$0 [DEVICE] <NAME>" \
	&& exit

[ -z "$mountName" ] \
	&& mountName="$(echo $device | tr '/' ':')"


mountLoc="/mnt/$user/$mountName"
uid=$(id -u)
gid=$(id -u)


doer=$(Doer)
echo "Using $doer to aquire root privileges"
set -xe
$doer mkdir -p "$mountLoc"
$doer mount -o rw,uid=$uid,gid=$gid "$device" "$mountLoc"
set +e

echo "Mounted $device on $mountLoc"

