#!/usr/bin/env bash

m="$(free -m | awk 'NR == 2 { printf("%d", $2 * 0.90)}')"
CPU_CORES=$(nproc)
RAM=$m
SSH_PORT=20022
CDROM="$(echo $@ | grep -E '*\.iso')"
SOUND_HW="-device intel-hda -device hda-duplex -device AC97 -device gus -device ES1370 -device sb16 -device adlib -device cs4231a"

qemu-system-x86_64 -enable-kvm -boot menu=on \
    -cpu host -smp ${CPU_CORES} \
    -m ${RAM} \
    ${SOUND_HW}\
    -net user,hostfwd=tcp::${SSH_PORT}-:22 \
    -net nic \
    -vga virtio \
    -cdrom ${CDROM}
