#!/bin/sh

user=$USER
device=$1
superdoer=$(which doas)
# Use sudo if doas is not found
[ -z "$superdoer" ] \
	&& superdoer=$(which sudo)

[ -z "$device" ] && exit

$superdoer mkdir -p "/mnt/$user"
$superdoer mount "$device" "/mnt/$user"
$superdoer chown ${user}:${user} -hR "/mnt/$user"
$superdoer chmod 0777 -R "/mnt/$user"

echo "Mounted $device on /mnt/$user"

