#!/bin/sh

user=$USER

if [ -z "$(ls /sys/block | grep -E 'zram')" ]; then
    $(Doer) modprobe zram
    test -z "$size" && size="3G"
    $(Doer) sh -c "echo lz4 > /sys/block/zram0/comp_algorithm && echo $size > /sys/block/zram0/disksize"
    $(Doer) mkfs.ext4 /dev/zram0
    $(Doer) mkdir -p /mnt/$user
    $(Doer) mount /dev/zram0 /mnt/$user
    $(Doer) rm -rf /mnt/$user/"lost+found"
    $(Doer) chown -R 644 /mnt
    $(Doer) sh -c "chown -R $user /mnt/$user && chgrp -R $user /mnt/$user"

    chmod -R 755 "/mnt/$user"
else
    echo 'ZRAM active, refuse to run'
fi
