#!/bin/sh

PATH="/usr/sbin:$PATH"
{
	echo "TODO: THIS SCRIPT IS BROKEN"
	exit 1
}

[ $(id -u) = "0" ] \
	|| { echo "This script must be run as root."; exit 1; }

umount /dev/zram0
rmmod zram
# rm -rf /mnt/$user
