#!/bin/sh

PATH="/usr/sbin:$PATH"
size="$1"
user="$2"

{
	echo "TODO: THIS SCRIPT IS BROKEN"
	exit 1
}

[ $(id -u) = "0" ] \
	|| { echo "This script must be run as root."; exit 1; }

[ -z "$size" ] \
	&& { echo "$(basename $0) SIZE [USER]"; exit 1; }

[ -z "$user" ] \
	&& user="root"

if [ -z "$(ls /sys/block | grep -E 'zram')" ]; then
	set -xe
    modprobe zram

    echo lz4 > /sys/block/zram0/comp_algorithm
	echo $size > /sys/block/zram0/disksize
	parted -a optimal /dev/zram0 mklabel gpt
	parted -a optimal /dev/zram0 mkpart primary 0% 100%
    mkfs.ext4 /dev/zram0

	uid=$(id -u $user)
	gid=$(id -u $user)
	mkdir -p /mnt/$user
	mount -o rw,uid=$uid,gid=$gid /dev/zram0 /mnt/$user

else
    echo 'ZRAM active, refuse to run'
fi
